[package]
name = "morse"
version = "0.1.0"
edition = "2021"

[dependencies]
pulse = { version = "2.0", package = "libpulse-binding" }
psimple = { version = "2.0", package = "libpulse-simple-binding" }
